environment: &env
  CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
  CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
  TZ: "/usr/share/zoneinfo/America/Toronto"

defaults: &defaults
  working_directory: ~/reduxicle
  environment:
    <<: *env
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dep-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dep-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - "node_modules"
              - "packages/reduxicle-core/node_modules"
              - "packages/reduxicle-dialog/node_modules"
              - "packages/reduxicle-react-router/node_modules"
              - "packages/reduxicle-redux-form/node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-core:
    <<: *defaults
    parallelism: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare to build
          command: cp -R /tmp/workspace/. .
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: yarn build --core
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-non-core:
    <<: *defaults
    parallelism: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare to build
          command: cp -R /tmp/workspace/. .
      - run:
          name: Build
          environment:
            NODE_ENV: production
          command: yarn build --non-core
  test:
    <<: *defaults
    parallelism: 1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare to test
          command: cp -R /tmp/workspace/. .
      - run:
          name: Test
          command: yarn test
workflows:
  version: 2
  workflow:
    jobs:
      - prepare
      - build-core:
          requires:
            - prepare        
      - build-non-core:
          requires:
            - build-core
      - test:
          requires:
            - build-core
